// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/Ghjattu/cloud-disk/services/repository/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: UploadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/exist/:hash",
				Handler: CheckFileExistHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
