// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UserInfoReq struct {
	ID int64 `json:"id"`
}

type UserInfoResp struct {
	Name string `json:"name"`
}
