// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Token string `json:"token"`
}

type LoginReq struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type GetGithubLoginURLResp struct {
	URL string `json:"url"`
}

type GithubCallbackReq struct {
	Code string `path:"code"`
}

type GithubCallbackResp struct {
	UserName string `json:"user_name"`
	Token    string `json:"token"`
}
