// Code generated by goctl. DO NOT EDIT.
package types

type UploadFileReq struct {
	FileHash    string `json:"file_hash"`
	TotalChunks int    `json:"total_chunks"`
	ChunkHash   string `json:"chunk_hash"`
}

type UploadFileResp struct {
	FileSuccess  bool   `json:"file_success"`
	ChunkSuccess bool   `json:"chunk_success"`
	ChunksCount  int    `json:"chunks_count"`
	FileID       int64  `json:"file_id"`
	FileURL      string `json:"file_url"`
}

type CheckFileExistReq struct {
	Hash string `path:"hash"`
}

type CheckFileExistResp struct {
	Exist      bool     `json:"exist"`
	FileID     int64    `json:"file_id"`
	FileURL    string   `json:"file_url"`
	ChunksHash []string `json:"chunks_hash"`
}
