// Code generated by goctl. DO NOT EDIT.
package types

type UploadFileReq struct {
	FileName    string `json:"file_name"`
	FileSize    int64  `json:"file_size"`
	FileHash    string `json:"file_hash"`
	TotalChunks int    `json:"total_chunks"`
	ChunkHash   string `json:"chunk_hash"`
	ChunkNum    int    `json:"chunk_num"`
}

type UploadFileResp struct {
	StatusMsg    string `json:"status_msg"`
	FileSuccess  bool   `json:"file_success"`
	ChunkSuccess bool   `json:"chunk_success"`
	ChunksCount  int    `json:"chunks_count"`
	FileID       int64  `json:"file_id"`
	FileURL      string `json:"file_url"`
}

type CheckFileExistReq struct {
	Hash string `path:"hash"`
}

type CheckFileExistResp struct {
	Exist      bool     `json:"exist"`
	FileID     int64    `json:"file_id"`
	FileURL    string   `json:"file_url"`
	ChunksHash []string `json:"chunks_hash"`
}

type GetFileListResp struct {
	FileID   int64  `json:"file_id"`
	FileName string `json:"file_name"`
	FileSize int64  `json:"file_size"`
	FileURL  string `json:"file_url"`
}
